<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-5QH6F0R" failures="2" tests="2" name="BankingApp Test" time="7.07" errors="0" timestamp="02 Aug 2023 07:58:57 GMT">
  <testcase classname="com.inetbanking.testCases.TC_loginTest_001" name="loginTest" time="0.473">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetbanking.testCases.TC_loginTest_001.loginTest(TC_loginTest_001.java:37)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.inetbanking.testCases.TC_loginTest_001" name="loginTest" time="0.487">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentReports.createTest(String)&amp;quot; because &amp;quot;this.extent&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentReports.createTest(String)" because "this.extent" is null
at com.inetbanking.utilities.Reporting.onTestFailure(Reporting.java:54)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- BankingApp Test -->
